#!/bin/bash

set -e

cd "$(dirname "$0")/.."

echo "==> Installing gem dependencies…"
bundle check --path vendor/gems &>/dev/null || {
  time bundle config set path 'vendor/gems'
  time bundle install
  time bundle binstubs --all
}

echo "==> Installing node dependencies…"
npm install
