#!/bin/sh

set -e

cd "$(dirname "$0")/.."

if [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }

  echo "==> Installing Ruby…"
  brew bootstrap-rbenv-ruby

  echo "==> Installing Node…"
  brew bootstrap-nodenv-node
fi

echo "==> Installing gem dependencies…"
bundle check --path vendor/gems >/dev/null 2>&1  || {
  bundle install --path vendor/gems --quiet --without production
}

echo "==> Installing node dependencies…"
npm install
