#!/bin/bash
set -e

cd "$(dirname "$0")/.."

gem install bundler

./script/setup

set +e

RUBY_VERSION="$(cat .ruby-version)"
echo "==> Checking for Ruby $RUBY_VERSION in Gemfile.lock..."
if grep -o "ruby $RUBY_VERSION.*" Gemfile.lock
then
  RUBY_GREP_EXIT="0"
else
  echo "Could not find $RUBY_VERSION in Gemfile.lock!"
  RUBY_GREP_EXIT="1"
fi

bundle exec rake test
RAKE_EXIT="$?"

bundle exec rubocop
RUBOCOP_EXIT="$?"
[[ "$RUBY_GREP_EXIT" == 0 && "$RAKE_EXIT" == 0 && "$RUBOCOP_EXIT" == 0 ]]
