#!/usr/bin/env ruby
require "html-proofer"

url_ignores = [
  "http://comcast.com",
]

HTMLProofer.check_directories(
  ["_site"],
  enforce_https: false,
  ignore_status_codes: [429],
  ignore_urls: url_ignores,
  only_4xx: true,
).run
